name: .NET Core

on:
  push:
    branches: 
    - main 
  pull_request:
    branches: 
    - main 

env:
  CI: false
  AZURE_WEBAPP_NAME: demoa0fc6  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'd:\a\TailwindTraders-Website-Drop'    
  AZURE_WEBAPP_PROJECT_PATH: 'D:\a\TailwindTraders-Website\TailwindTraders-Website\TailwindTraders.Website\Source\Tailwind.Traders.Web\Tailwind.Traders.Web.csproj'    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.6   

    - name: Install dependencies in client app
      working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web/ClientApp
      run: npm install

    - name: Build and publish with dotnet
      working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web
      run: |
        dotnet build --configuration Release
        dotnet publish -c Release -o publish

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_2 }}

    - uses: azure/appservice-settings@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore ${{ env.AZURE_WEBAPP_PROJECT_PATH }}  --verbosity Detailed
    - name: Build
      run: dotnet build ${{ env.AZURE_WEBAPP_PROJECT_PATH }} --configuration Release --no-restore  --verbosity Detailed    
    - name: Publish
      run: dotnet publish ${{ env.AZURE_WEBAPP_PROJECT_PATH }} --configuration release --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --verbosity Detailed      
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.TailwindtradersSecret }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
